firstcrack/events/urls.py
from django.urls import path
from . import views

app_name = 'events'

urlpatterns = [
    path('', views.EventsList.as_view(), name='events'),
    path('<int:pk>/', views.EventDetail.as_view(), name='event-detail'),
    path('calendar/', views.calendar, name="calendar")

]

firstcrack/firstcrack/urls.py
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('events/', include('events.urls')),
    path('sales/', include('sales.urls')),
    path('', include('home.urls')),
    # Tailwind browser reload
    path("__reload__/", include("django_browser_reload.urls")),
]

firstcrack/home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
]

firstcrack/sales/urls.py
from django.urls import path
from . import views

app_name = 'sales'

urlpatterns = [
    path('', views.SalesList.as_view(), name='sales'),
    path('<int:pk>/', views.SaleDetail.as_view(), name='sale-detail'),
    path('products/', views.ProductList.as_view(), name="products")
    
        
]

firstcrack/events/models.py
from django.db import models

# Create your models here.
class Employee(models.Model):
    first_name = models.CharField(max_length=255, verbose_name="First name of employee")
    last_name = models.CharField(max_length=255, verbose_name="Last name of employee", blank=True)

    def __str__(self):
        return self.first_name + " " + self.last_name

class Event(models.Model):
    CONFIRMED = 'Confirmed'
    PENDING = 'Pending'
    CANCELED = 'Canceled'
    COMPLETED = 'Completed'

    STATUS = [
       (CONFIRMED, 'Confirmed'),
       (PENDING, 'Pending'),
       (CANCELED, 'Canceled'),
       (COMPLETED, 'Completed'),

    ]


    name = models.CharField(
            max_length=255,
            verbose_name="Name of the event"
            )
    description = models.TextField(
            verbose_name="Short description of our event",
            blank=True
            )
    start_date = models.DateTimeField(blank=True, null=True)
    end_date = models.DateTimeField(blank=True, null=True)
    status = models.CharField(
            max_length=255,
            verbose_name="Current state of the event",
            choices=STATUS,
            default=PENDING
            )

    staff = models.ManyToManyField(Employee, blank=True, related_name="events")
    
    def __str__(self):
        return self.name

firstcrack/home/models.py
from django.db import models

# Create your models here.

firstcrack/sales/models.py
from django.db import models
from address.models import AddressField
# Create your models here.

class Product(models.Model):
    name = models.CharField(max_length=255)
    
    def __str__(self):
        return self.name

class ProductVariation(models.Model):
    specification = models.CharField(max_length=255)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True, blank=True)
    retail_price = models.DecimalField(decimal_places=2, max_digits=10)
    purchase_price = models.DecimalField(decimal_places=2, max_digits=10)

    def __str__(self):
        return self.product.name + " | " + self.specification 


class Client(models.Model):
    name = models.CharField(max_length=255)
    address = AddressField(blank=True, null=True)

    def __str__(self):
        return self.name


class Sale(models.Model):

    NEW = 'New order'
    ACCEPTED = 'Accepted'
    DECLINED = 'Declined'
    PROCESSED = 'In process'
    DELIVRERD = 'Deliverd to customer'
    INVOICED = 'Invoice sent'
    PAYED = 'Invoice payed'

    STATUS = [
            (NEW, 'New order'),
            (ACCEPTED, 'Accepted'),
            (DECLINED, 'Declined'),
            (PROCESSED, 'In process'),
            (DELIVRERD, 'Delivered to customer'),
            (INVOICED, 'Invoice sent'),
            (PAYED, 'Invoice payed')
            ]
    order_date = models.DateTimeField(auto_now_add=True)
    status = models.CharField(
            max_length = 255, 
            verbose_name = "State of the current order",
            choices = STATUS,
            default = NEW
            )
    delivery_date = models.DateField(blank=True)
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    purchases = models.ManyToManyField(ProductVariation, through="Purchase")
    def __str__(self):
        return str(self.id)

class Purchase(models.Model):
    quantity = models.IntegerField()
    sale = models.ForeignKey(Sale, on_delete=models.CASCADE)
    product = models.ForeignKey(ProductVariation, on_delete=models.CASCADE)

firstcrack/sales/forms.py
from django import forms
from .models import Sale, Purchase

class SaleForm(forms.ModelForm):
    class Meta:
        model = Sale
        fields = ['client', 'delivery_date']

class PurchaseForm(forms.ModelForm):
    class Meta:
        model = Purchase
        fields = ['product', 'quantity']

firstcrack/events/views.py
from django.shortcuts import render
from django.views import generic
from .models import Event
# Create your views here.
class EventsList(generic.ListView):
    model = Event

def calendar(request):
    events = Event.objects.all()

    context = {
            'events': events
            }
    return render(request, 'events/calendar.html', context)

class EventDetail(generic.DetailView):
    model = Event

firstcrack/home/views.py
from django.shortcuts import render
from events.models import Event

# Create your views here.
def index(request):
    events = Event.objects.all()

    context = {
            'events': events
            }
    return render(request, 'home/index.html', context)

firstcrack/sales/views.py
from django.shortcuts import render
from .models import Sale, ProductVariation
from django.views import generic
# Create your views here.

class SalesList(generic.ListView):
    model = Sale

class SaleDetail(generic.DetailView):
    model = Sale

class ProductList(generic.ListView):
    model = ProductVariation

firstcrack/events/templates/events/calendar.html
{% extends 'base.html' %}
<div>
    {% block content %}
    <h1 class="mt-12 ml-12 font-sans uppercase">Calendar view</h1>
    {% endblock %}
</div>
<script>
</script>
</div>

firstcrack/events/templates/events/event_detail.html
{% extends 'theme/base.html' %}
{% block sidebar %}
    {% include 'theme/sidebar.html' %}
{% endblock sidebar %}
{% block content %}
    <h2 class="text-4xl font-sans font-thin uppercase dark:text-white">{{ event.name }}</h2>
    <hr class="h-px my-8 bg-slate-200 border-0 dark:bg-slate-700">
    <p class="mt-4">
        <strong>Starting date:</strong> {{ event.start_date }}
    </p>
    <p>
        <strong>End date</strong> {{ event.end_date }}
    </p>
    <h3 class="mt-4 font-sans uppercase dark:text-white">Employees</h3>
    <p>
        {% for employee in event.staff.all %}
            <a href="#"></a> <a href="#"
    class="bg-blue-100 hover:bg-blue-200 text-blue-800 text-xs font-semibold mr-2 px-2.5 py-0.5 rounded dark:bg-gray-700 dark:text-blue-400 border border-blue-400 inline-flex items-center justify-center">{{ employee.first_name }} {{ employee.last_name }}</a>
        </a>
    {% endfor %}
</p>
{% endblock content %}

firstcrack/events/templates/events/event_list.html
{% extends 'theme/base.html' %}
{% block sidebar %}
    {% include 'theme/sidebar.html' %}
{% endblock sidebar %}
{% block content %}
    <h1 class="font-sans uppercase">List of all events</h1>
    <p>
        Total number of events: <strong>{{ object_list|length }}</strong>
    </p>
    <div class="relative overflow-x-auto shadow-lg sm:rounded-lg mt-6">
        <table class="w-full text-sm text-left text-slate-500 dark:text-slate-400">
            <thead class="text-xs text-slate-700 uppercase bg-slate-50 dark:bg-slate-700 dark:text-slate-400">
                <tr>
                    <th scope="col" class="px-6 py-3">Event name</th>
                    <th scope="col" class="px-6 py-3">Start date</th>
                    <th scope="col" class="px-6 py-3">End date</th>
                    <th scope="col" class="px-6 py-3">Employees</th>
                    <th scope="col" class="px-6 py-3">
                        <span class="sr-only">View</span>
                    </th>
                </tr>
            </thead>
            <tbody>
                {% for event in object_list %}
                    <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
                        <th scope="row"
                            class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                            {{ event.name }}
                        </th>
                        <td class="px-6 py-4">{{ event.start_date }}</td>
                        <td class="px-6 py-4">{{ event.end_date }}</td>
                        <td class="px-6 py-4">
                            {% for employee in event.staff.all %}
                                <span class="bg-slate-200 text-green-800 text-xs font-medium mr-2 px-2.5 py-0.5 rounded-full dark:bg-green-900 dark:text-green-300">{{ employee.first_name }} {{ employee.last_name }}</span>
                            {% endfor %}
                        </td>
                        <td class="px-6 py-4 text-right">
                            <a href="{% url "events:event-detail" pk=event.pk %}"
                               class="font-medium text-blue-600 dark:text-blue-500 hover:underline">View</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

firstcrack/home/templates/home/index.html
{% extends 'theme/base.html' %}
<div>
    {% block content %}
        <h1 class="mt-32 text-4xl italic font-extrabold text-center font-headings lg:text-8xl text-slate-700">firstcrack.</h1>
        <div class="container p-4 mx-auto mt-16 grid lg:grid-cols-3 sm:grid-cols-2 grid-cols-1 gap-6">
            <a href="{% url 'events:events' %}"
               class="transition p-8 rounded-lg shadow-2xl hover:bg-slate-50">
                <h2 class="text-2xl font-bold font-headings">Events</h2>
                <p class="text-center font-headings text-8xl text-slate-400">{{ events.count }}</p>
                <p class="mt-6 font-sans text-xs text-center text-slate-400">Upcoming events this month</p>
            </a>
            <a href="{% url 'sales:sales' %}"
               class="transition p-8 rounded-lg shadow-2xl hover:bg-slate-50">
                <h2 class="text-2xl font-bold font-headings">Sales</h2>
                <p class="text-center font-headings text-8xl text-slate-400">{{ open_sales.count }}</p>
                <p class="mt-6 font-sans text-xs text-center text-slate-400">Sales to be completed</p>
            </a>
            <a href="{% url 'sales:products' %}"
               class="transition p-8 rounded-lg shadow-2xl hover:bg-slate-50">
                <h2 class="text-2xl font-bold font-headings">Products</h2>
                <p class="text-center font-headings text-8xl text-slate-400">{{ all_products.count }}</p>
                <p class="mt-6 font-sans text-xs text-center text-slate-400">Total number of products</p>
            </a>
        </div>
    {% endblock %}
</div>

firstcrack/sales/templates/sales/sale_detail.html
{% extends 'theme/base.html' %}
{% block sidebar %}
    {% include 'theme/sidebar.html' %}
{% endblock sidebar %}
{% block content %}
    <h2 class="font-sans text-4xl font-thin uppercase dark:text-white">
        # {{ sale.id }} <mark class="px-2 text-white bg-amber-300 rounded dark:bg-blue-500"> {{ sale.status }}
    </mark>
</h2>
<p class="mt-4"></p>
<hr class="h-px my-8 border-0 bg-slate-200 dark:bg-slate-700">
<p class="mt-4">
    <strong>Client:</strong> {{ sale.client }}
</p>
<p class="mt-4">
    <strong>Order date:</strong> {{ sale.order_date }}
</p>
<p class="mt-4">
    <strong>Delivery date:</strong> {{ sale.delivery_date }}
</p>
<h3 class="mt-6 font-headings text-2xö uppercase dark:text-white">Purchases</h3>
<div class="relative overflow-x-auto shadow-lg sm:rounded-lg">
    <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400 mt-6">
        <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
            <tr>
                <th scope="col" class="px-6 py-3">Quantity</th>
                <th scope="col" class="px-6 py-3">Product</th>
                <th scope="col" class="px-6 py-3">Variation</th>
                <th scope="col" class="px-6 py-3">Price</th>
            </tr>
        </thead>
        <tbody>
            {% for purchase in sale.purchases.all %}
                <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                    <td class="px-6 py-4">{{ purchase.purchase_set.first.quantity }}</td>
                    <th scope="row"
                        class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                        {{ purchase.product }}
                    </th>
                    <td class="px-6 py-4">{{ purchase.specification }}</td>
                    <td class="px-6 py-4">{{ purchase.retail_price }} &euro;</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
</p>
{% endblock content %}

firstcrack/sales/templates/sales/sale_list.html
{% extends 'theme/base.html' %}
{% block sidebar %}
    {% include 'theme/sidebar.html' %}
{% endblock sidebar %}
{% block content %}<h1 class="font-sans uppercase">List of all sales</h1>{% endblock %}

firstcrack/theme/templates/theme/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>firstcrack.</title>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta http-equiv="X-UA-Compatible" content="ie=edge" />
        <link rel="stylesheet" href="https://use.typekit.net/pjz3krm.css" />
        {% tailwind_css %}
    </head>
    <body class="leading-normal tracking-normal">
        {% block sidebar %}
        {% endblock sidebar %}
        <div class="w-full h-screen overflow-y-auto ">
            <section class="container px-6 mx-auto">
                {% block content %}{% endblock %}
            </section>
        </div>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.8.1/flowbite.min.js"></script>
</body>
</html>

firstcrack/theme/templates/theme/sidebar.html
<!-- drawer init and show -->
<div class="container px-6 mx-auto mb-6">
  <button
    class="mt-12 transition text-slate-400 hover:text-slate-500"
    type="button"
    data-drawer-target="drawer-navigation"
    data-drawer-show="drawer-navigation"
    aria-controls="drawer-navigation"
  >
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="currentColor"
      viewBox="0 0 24 24"
      stroke-width="1.5"
      stroke="currentColor"
      class="w-6 h-6"
    >
      <path
        stroke-linecap="round"
        stroke-linejoin="round"
        d="M2.25 12l8.954-8.955c.44-.439 1.152-.439 1.591 0L21.75 12M4.5 9.75v10.125c0 .621.504 1.125 1.125 1.125H9.75v-4.875c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125V21h4.125c.621 0 1.125-.504 1.125-1.125V9.75M8.25 21h8.25"
      />
    </svg>
  </button>
</div>
<!-- drawer component -->
<div
  id="drawer-navigation"
  class="fixed top-0 left-0 z-40 w-64 h-screen p-4 overflow-y-auto bg-white transition-transform -translate-x-full dark:bg-gray-800"
  tabindex="-1"
  aria-labelledby="drawer-navigation-label"
>
  <a href="https://flowbite.com/" class="flex items-center pl-2.5 mb-5">
    <span
      class="self-center text-2xl italic font-extrabold font-headings whitespace-nowrap dark:text-white"
      >firstcrack.</span
    >
  </a>

  <button
    type="button"
    data-drawer-hide="drawer-navigation"
    aria-controls="drawer-navigation"
    class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-3 absolute top-2.5 right-2.5 inline-flex items-center dark:hover:bg-gray-600 dark:hover:text-white"
  >
    <svg
      aria-hidden="true"
      class="w-5 h-5"
      fill="currentColor"
      viewBox="0 0 20 20"
      xmlns="http://www.w3.org/2000/svg"
    >
      <path
        fill-rule="evenodd"
        d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"
        clip-rule="evenodd"
      ></path>
    </svg>
    <span class="sr-only">Close menu</span>
  </button>
  <div class="py-4 overflow-y-auto">
    <ul class="font-medium space-y-2">
      <li>
        <a
          href="{% url 'home:index' %}"
          class="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group"
        >
          <svg
            class="w-5 h-5 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white"
            aria-hidden="true"
            xmlns="http://www.w3.org/2000/svg"
            fill="currentColor"
            viewBox="0 0 22 21"
          >
            <path
              d="M16.975 11H10V4.025a1 1 0 0 0-1.066-.998 8.5 8.5 0 1 0 9.039 9.039.999.999 0 0 0-1-1.066h.002Z"
            />
            <path
              d="M12.5 0c-.157 0-.311.01-.565.027A1 1 0 0 0 11 1.02V10h8.975a1 1 0 0 0 1-.935c.013-.188.028-.374.028-.565A8.51 8.51 0 0 0 12.5 0Z"
            />
          </svg>
          <span class="ml-3">Dashboard</span>
        </a>
      </li>
      <li>
        <a
          href="{% url 'events:events' %}"
          class="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group"
        >
          <svg
            class="flex-shrink-0 w-5 h-5 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white"
            aria-hidden="true"
            xmlns="http://www.w3.org/2000/svg"
            fill="currentColor"
            viewBox="0 0 18 18"
          >
            <path
              d="M0 18a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V8H0v10Zm14-7.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-1Zm0 4a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-1Zm-5-4a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-1Zm0 4a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-1Zm-5-4a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-1Zm0 4a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-1ZM20 4a2 2 0 0 0-2-2h-2V1a1 1 0 0 0-2 0v1h-3V1a1 1 0 0 0-2 0v1H6V1a1 1 0 0 0-2 0v1H2a2 2 0 0 0-2 2v2h20V4Z"
            />
          </svg>
          <span class="flex-1 ml-3 whitespace-nowrap">Events</span>
          <span
            class="inline-flex items-center justify-center px-2 ml-3 text-sm font-medium text-gray-800 bg-gray-100 rounded-full dark:bg-gray-700 dark:text-gray-300"
            >{{all_events.count}}</span
          >
        </a>
      </li>
      <li>
        <a
          href="{% url 'sales:sales' %}"
          class="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group"
        >
          <svg
            class="flex-shrink-0 w-5 h-5 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white"
            aria-hidden="true"
            xmlns="http://www.w3.org/2000/svg"
            fill="currentColor"
            viewBox="0 0 20 20"
          >
            <path
              d="M18 0H2a2 2 0 0 0-2 2v10a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2ZM2 12V6h16v6H2Z"
            />
            <path
              d="M6 8H4a1 1 0 0 0 0 2h2a1 1 0 0 0 0-2Zm8 0H9a1 1 0 0 0 0 2h5a1 1 0 1 0 0-2Z"
            />
          </svg>
          <span class="flex-1 ml-3 whitespace-nowrap">Sales</span>
          <span
            class="inline-flex items-center justify-center w-3 h-3 p-3 ml-3 text-sm font-medium text-blue-800 bg-blue-100 rounded-full dark:bg-blue-900 dark:text-blue-300"
            >{{open_sales.count}}</span
          >
        </a>
      </li>
      <li>
        <a
          href="{% url 'sales:products' %}"
          class="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group"
        >
          <svg
            class="flex-shrink-0 w-5 h-5 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white"
            aria-hidden="true"
            xmlns="http://www.w3.org/2000/svg"
            fill="currentColor"
            viewBox="0 0 18 20"
          >
            <path
              d="M17 5.923A1 1 0 0 0 16 5h-3V4a4 4 0 1 0-8 0v1H2a1 1 0 0 0-1 .923L.086 17.846A2 2 0 0 0 2.08 20h13.84a2 2 0 0 0 1.994-2.153L17 5.923ZM7 9a1 1 0 0 1-2 0V7h2v2Zm0-5a2 2 0 1 1 4 0v1H7V4Zm6 5a1 1 0 1 1-2 0V7h2v2Z"
            />
          </svg>
          <span class="flex-1 ml-3 whitespace-nowrap">Products</span>
        </a>
      </li>
      <li>
        <a
          href="#"
          class="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group"
        >
          <svg
            class="flex-shrink-0 w-5 h-5 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white"
            aria-hidden="true"
            xmlns="http://www.w3.org/2000/svg"
            fill="currentColor"
            viewBox="0 0 20 18"
          >
            <path
              d="M14 2a3.963 3.963 0 0 0-1.4.267 6.439 6.439 0 0 1-1.331 6.638A4 4 0 1 0 14 2Zm1 9h-1.264A6.957 6.957 0 0 1 15 15v2a2.97 2.97 0 0 1-.184 1H19a1 1 0 0 0 1-1v-1a5.006 5.006 0 0 0-5-5ZM6.5 9a4.5 4.5 0 1 0 0-9 4.5 4.5 0 0 0 0 9ZM8 10H5a5.006 5.006 0 0 0-5 5v2a1 1 0 0 0 1 1h11a1 1 0 0 0 1-1v-2a5.006 5.006 0 0 0-5-5Z"
            />
          </svg>
          <span class="flex-1 ml-3 whitespace-nowrap">Users</span>
        </a>
      </li>
      <li>
        <a
          data-modal-target="authentication-modal"
          data-modal-toggle="authentication-modal"
          href="#"
          class="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group"
        >
          <svg
            class="flex-shrink-0 w-5 h-5 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white"
            aria-hidden="true"
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 18 16"
          >
            <path
              stroke="currentColor"
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M1 8h11m0 0L8 4m4 4-4 4m4-11h3a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2h-3"
            />
          </svg>
          <span class="flex-1 ml-3 whitespace-nowrap">Sign In</span>
        </a>
      </li>
      <li>
        <a
          href="#"
          class="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group"
        >
          <svg
            class="flex-shrink-0 w-5 h-5 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white"
            aria-hidden="true"
            xmlns="http://www.w3.org/2000/svg"
            fill="currentColor"
            viewBox="0 0 20 20"
          >
            <path
              d="M5 5V.13a2.96 2.96 0 0 0-1.293.749L.879 3.707A2.96 2.96 0 0 0 .13 5H5Z"
            />
            <path
              d="M6.737 11.061a2.961 2.961 0 0 1 .81-1.515l6.117-6.116A4.839 4.839 0 0 1 16 2.141V2a1.97 1.97 0 0 0-1.933-2H7v5a2 2 0 0 1-2 2H0v11a1.969 1.969 0 0 0 1.933 2h12.134A1.97 1.97 0 0 0 16 18v-3.093l-1.546 1.546c-.413.413-.94.695-1.513.81l-3.4.679a2.947 2.947 0 0 1-1.85-.227 2.96 2.96 0 0 1-1.635-3.257l.681-3.397Z"
            />
            <path
              d="M8.961 16a.93.93 0 0 0 .189-.019l3.4-.679a.961.961 0 0 0 .49-.263l6.118-6.117a2.884 2.884 0 0 0-4.079-4.078l-6.117 6.117a.96.96 0 0 0-.263.491l-.679 3.4A.961.961 0 0 0 8.961 16Zm7.477-9.8a.958.958 0 0 1 .68-.281.961.961 0 0 1 .682 1.644l-.315.315-1.36-1.36.313-.318Zm-5.911 5.911 4.236-4.236 1.359 1.359-4.236 4.237-1.7.339.341-1.699Z"
            />
          </svg>
          <span class="flex-1 ml-3 whitespace-nowrap">Sign Up</span>
        </a>
      </li>
    </ul>
  </div>
</div>

{% include 'home/login_modal.html' %}